### ISSUE TITLE
Requests too many permissions

### ISSUE THREAD

**Issue by TheLastProject** [simple-login/browser-extension#145] opened 2022-05-24 07:57 UTC
<img width="426" alt="Screenshot 2022-05-24 at 09 53 43" src="https://user-images.githubusercontent.com/1885159/169979175-e57371aa-71d6-41ef-89fe-0a28edfdfd0a.png">

Firefox just offered me to update from 2.5.1 to "the latest version". For something that claims to protect your privacy, this is way too much to ask.

Looking at 2.5.1, these used to be optional permissions: https://github.com/simple-login/browser-extension/blob/2.5.1/src/manifest.json
Now, they're required: https://github.com/simple-login/browser-extension/blob/2.6.3/src/manifest.json

Looks like https://github.com/simple-login/browser-extension/pull/123 may fix this? But honestly, it worries me that requiring access for every single thing the user opens was added this haphazardly without any apparent consideration for the security and trust issues it opens.

**Comment by nguyenkims** [comment] 2022-05-24 10:03
@TheLastProject hey we have a lot of debate about this change in the team as well and here are the reasons we decide to ask for this permission at installation time:

- asking this permission upfront to simplify the onboarding process: currently this process is lengthy and people might never see the convenience of having the SL icon on the email field. Whereas this is the best way to get used to aliases in our opinion.
- other similar extensions ask for this permission upfront (bitwarden, 1password, firefox relay, etc.)
- with the manifest v3, we can better fine tune this permission. The manifest v3 isn't currently supported by other browsers  though so we haven't started porting the extension to this format.
- At the end of the day, it's all about trust. SimpleLogin is entrusted to handling people emails thanks to our transparency so we don't think there should be an issue with this extension permission.

We can also consider the possibility of forking another version for SimpleLogin extension that doesn't ask for this permission.

**Comment by roelandjansen** [comment] 2022-05-24 10:08
I also support @TheLastProject consideration to revert. 

To simplify the access to my house, I removed the locks. handy but not secure.
And at the end it's all about trust. I hope nobody else but my family enters the building.

**Comment by TheLastProject** [comment] 2022-05-24 11:10
> asking this permission upfront to simplify the onboarding process: currently this process is lengthy and people might never see the convenience of having the SL icon on the email field. Whereas this is the best way to get used to aliases in our opinion.

I do not see how this cannot be solved by just instantly asking the permission after first run, so that those who don't use this feature don't have to give it.

> other similar extensions ask for this permission upfront (bitwarden, 1password, firefox relay, etc.)

Which for me is a good reason to use SimpleLogin instead of those services. Well, was.

> with the manifest v3, we can better fine tune this permission. The manifest v3 isn't currently supported by other browsers though so we haven't started porting the extension to this format.

Why not simply wait until manifest v3 then to implement this default, instead of now forcing users to choose between security or updates?

> At the end of the day, it's all about trust. SimpleLogin is entrusted to handling people emails thanks to our transparency so we don't think there should be an issue with this extension permission.

Yeah, well, I don't trust you with complete access to all my browser tabs. And even if I did, I don't trust you to not accidentally make a code mistake at some point that allows a hacker this access because of the wide-open permissions, if only for the simple fact that everyone makes mistakes sometimes.

> We can also consider the possibility of forking another version for SimpleLogin extension that doesn't ask for this permission.

That is a work-around I guess, but then you literally have the worst of both worlds because now users will have to switch add-ons to enable an optional feature and you have to maintain 2 add-ons. Doing this doesn't really make sense to me especially given your claimed goal was to "reduce complexity".

**Comment by ChrisTiffin** [comment] 2022-05-26 16:51
> At the end of the day, it's all about trust. SimpleLogin is entrusted to handling people emails thanks to our transparency so we don't think there should be an issue with this extension permission.

I want to echo @TheLastProject here - I absolutely do not trust you with complete access to all of my browser tabs - why should I? Because we trust you with emails, we should also just trust you with whatever else? Please try to appreciate how inappropriate, even arrogant, that view is for a company like yours. You're pitching your product at people who are privacy and security conscious and would prefer to not trust where possible.


> with the manifest v3, we can better fine tune this permission. The manifest v3 isn't currently supported by other browsers though so we haven't started porting the extension to this format.

> We can also consider the possibility of forking another version for SimpleLogin extension that doesn't ask for this permission.

Is there a timeline for either of these? I'm unwilling to grant the newly required permissions, and I don't think it's possible to roll back to a previous version?

**Comment by nguyenkims** [comment] 2022-05-26 18:11
Hi all,

The upcoming versions of SimpleLogin extension will add more interactivity to the currently static SL icon and users won't benefit from these improvements with this permission disabled. We took the decision of asking this permission upfront and unfortunately won't go back on it.

I totally understand your concerns. Similarly to those who don't trust SimpleLogin server (and decide to self host SL), there are 3 solutions IMO:

1) We can provide a build with this permission disabled automatically for every new release. This doesn't add any complexity to our workflow.

2) Build the extension yourself and remove the permission from the manifest.json file. We recommend this option if you want to further tweak the extension. Every new release is tagged so you can easily download the version you want.

3) Use our previous version at https://github.com/simple-login/browser-extension/releases/tag/2.5.2 . You can then disable the auto update to avoid newer version from being installed.

**Comment by ngxson** [comment] 2022-05-26 18:52
My personal thought is that it will be more pratical to ask the user whether to enable the permission. For example, although Apple's strategy is to make things simple, Apple is also the one who pioneers in adding the permission prompts. A well-designed UX should make people more confident on their actions, while doesn't add much complications.

On the flip side, I also want to blame chrome (and maybe firefox) for that: Why can't they just allow user to disable **any** permission of **any** extension? There're extensions that I install once for doing specific tasks. I don't want to give them any permissions, but the fact that the browser doesn't give me this flexibility makes me quite mad.

**Comment by TheLastProject** [comment] 2022-05-26 19:34
> Why can't they just allow user to disable **any** permission of **any** extension?

Optional permissions can be disabled at any time. That's how it was for this extension too until SimpleLogin changed it.

**Comment by nguyenkims** [comment] 2022-05-27 16:59
For info, we have removed the "tabs" permission which will be included in the next version https://github.com/simple-login/browser-extension/pull/148 .  We have also created a Firefox add-on without the "Access your data for all websites" permission, it's currently in review.

For the context, one of challenges for SimpleLogin extension is people don't understand what is an email alias. This isn't a problem for people coming from SimpleLogin website but for those who discover the extension on the Chrome/Firefox store, it isn't easy to fully grasp this new concept. Our previous onboarding tries to explain what is an email alias but from what we see, most people just skip it. The new onboarding puts the alias in a more direct way that hopefully helps using aliases more mainstream.

I agree that the browser should allow users to disable any extension permission, whether optional or not. Unfortunately the extension permission seems to be rather an afterthought.

**Comment by nguyenkims** [comment] 2022-05-28 17:38
The extension without the "Access your data for all websites" permission is now available on https://addons.mozilla.org/en-US/firefox/addon/simplelogin-without-sl-icon/

**Closed by nguyenkims** 2022-05-28 17:38 UTC

**Comment by TheLastProject** [comment] 2022-05-30 07:08
Good start. but where is the source code of that version?

**Comment by nguyenkims** [comment] 2022-05-30 07:31
@TheLastProject it's the same code, it just has the permission removed when building.

**Comment by TheLastProject** [comment] 2022-07-25 08:05
The extension seems to no longer be available?

**Comment by nguyenkims** [comment] 2022-07-26 08:00
@TheLastProject firefox seems to detect an issue with the build, let us upload it again.

**Comment by nguyenkims** [comment] 2022-07-26 08:46
@TheLastProject the new version has been submitted.

**Comment by TheLastProject** [comment] 2022-07-28 11:21
Any clue how long this normally takes? I'm still not seeing anything on the URL and I sadly can't sideload the release 2.5.2 published on this GitHub as it isn't signed and Firefox blocks unsigned extensions in the default builds (and doesn't seem to offer any repo with auto-update for the "Developer Edition")

**Comment by nguyenkims** [comment] 2022-07-29 07:42
@TheLastProject I've been talking with Firefox reviewers since Wed as they don't seem to be able to reproduce the build. This seems to be the new review process in Firefox and we didn't have to go through this the last time.

You can also produce the build locally in the meantime:

```
# clone the repository
git clone git@github.com:simple-login/browser-extension.git && cd browser-extension

# check out the branch
git checkout no-sl-icon

# install dependencies, build and produce a zip file for the submission
npm i && npm run build && npm run build-zip

# the produced zip file should be in the dist-zip/ directory
ls dist-zip/

```

**Comment by TheLastProject** [comment] 2022-07-29 07:59
Sadly that also seems to create an unverified build that can't be installed in regular Firefox. Honestly, quite a frustrating change Mozilla made (I understand it from a protecting user perspective, but not allow this to be changed under an about:config flag and requiring a completely different browser version download that doesn't have proper Ubuntu packaging does make this a very annoying thing to deal with). Anyway, the verification requirement is more of a Firefox issue than a SimpleLogin issue and not something worth bothering you with :)

**Comment by nguyenkims** [comment] 2022-07-29 08:15
@TheLastProject I think the reviewers used the wrong command and produced a beta build which then doesn't have the same MD5 as the submitted zip. Hope this is the case and the review should be unblocked quickly.

**Comment by Termuellinator** [comment] 2022-08-24 05:54
Are there any news in regards to that less permission version?

**Comment by nguyenkims** [comment] 2022-08-24 06:42
Firefox now asks to provide a dedicated privacy policy for this version and doesn't accept the usual privacy we used at https://simplelogin.io/privacy/ . Unfortunately, we don't have time to write a privacy policy just for the extension, especially when this is just a formality (as there's practically no way to verify this in Firefox) and when there's no data collection in SimpleLogin. If possible, it'd be great if you can upload the build to your Firefox developer account, maybe your review process will have more luck.


> Please add a privacy policy to this add-on that details which user data is being sent and to what services. The critical things to describe in the policy are how your extension collects, uses, stores, and shares or discloses information about people.If your add-on makes it apparent to websites that it is installed, this must also be mentioned. The privacy policy should be about the extension only, not a copy of the website's privacy policy. It should also be the actual text, as opposed to a link to a privacy policy on a website. The privacy policy can be added in the add-on settings under “Manage Authors & License” on AMO.

**Comment by nguyenkims** [comment] 2022-08-24 15:00
@Termuellinator Currently we don't have a lot of requests for this "light" version so unfortunately it isn't high in our todo list (I tried to upload this version in my free time back then). To be honest, this new Firefox review process is painful enough that it'd take me some time to motivate myself to create a specific privacy policy for Firefox and go through the process again :). In the meantime, I suggest to check out the code, remove the permissions and build it.

**Comment by TheLastProject** [comment] 2023-01-18 13:22
[Firefox 109 has been released with Manifest v3 support](https://www.mozilla.org/en-US/firefox/109.0/releasenotes/). Does the version uploaded to Mozilla addons support it yet? I see no way to block access to all domains yet.

**Comment by nguyenkims** [comment] 2023-01-20 17:13
@TheLastProject we have supporting manifest v3 in our roadmap. Currently it's still using manifest v2.
